layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: :title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  facebook: rafidalhaqueofficial
  # hackerrank: your_username
  instagram: rafidalhaqueofficial
  # keybase: your_username
  linkedin: rafidalhaque
  # mastodon: your_username
  medium: rafidalhaque
  # stackoverflow: your_user_id
  telegram: rafidalhaqueofficial
  twitter: rafidalhaque
  # unsplash: your_username
  # vk: your_username
  website: http://rafidalhaque.xyz
  # youtube: your_username


# Uncomment It if you want to show your interest topics list on homepage  
# topics:
#  - name: C
#    web_url: https://github.com/topics/c
#    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/css/css.png
